-- Editor options (only values that differ from Neovim's defaults).
local cache = vim.fn.stdpath("cache")
for _, dir in ipairs({ "undo" }) do
	vim.fn.mkdir(cache .. "/" .. dir, "p")
end

local options = {
	undodir = cache .. "/undo//",
	spellfile = vim.fn.stdpath("config") .. "/spell/en.utf-8.add",
	autowrite = true,
	backupskip = "/tmp/*,$TMPDIR/*,$TMP/*,$TEMP/*,*/shm/*,/private/var/*,.vault.vim",
	breakat = [[\ \	;:,!?@*-+/]],
	breakindentopt = "shift:2,min:20",
	clipboard = "unnamedplus",
	cmdheight = 0,
	cmdwinheight = 5,
	complete = ".,w,b,k,kspell",
	completeopt = "fuzzy,menuone,noselect,popup",
	concealcursor = "niv",
	cursorline = true,
	diffopt = "filler,iwhite,internal,linematch:60,algorithm:patience",
	equalalways = false,
	errorbells = true,
	expandtab = true,
	fileencodings = "ucs-bom,utf-8,default,big5,latin1",
	fileformats = "unix,mac,dos",
	foldlevelstart = 99,
	formatoptions = "1jcroql",
	grepprg = "rg --hidden --vimgrep --smart-case --",
	helpheight = 12,
	history = 2000,
	ignorecase = true,
	infercase = true,
	jumpoptions = "stack,view",
	laststatus = 3,
	linebreak = true,
	list = true,
	listchars = "tab:»·,nbsp:+,trail:·,extends:→,precedes:←",
	mouse = "a",
	number = true,
	pumheight = 15,
	redrawtime = 1500,
	scrolloff = 12,
	sessionoptions = "buffers,curdir,folds,help,tabpages,winpos,winsize",
	shada = "!,'500,<50,@100,s10,h",
	shiftround = true,
	shiftwidth = 4,
	shortmess = "aoOTIcF",
	showbreak = "↳  ",
	showcmd = false,
	showmode = false,
	showtabline = 2,
	sidescrolloff = 10,
	signcolumn = "yes",
	smartcase = true,
	smartindent = true,
	smoothscroll = true,
	softtabstop = 4,
	splitbelow = true,
	splitkeep = "screen",
	splitright = true,
	swapfile = false,
	switchbuf = "usetab,uselast",
	synmaxcol = 2500,
	tabstop = 4,
	termguicolors = true,
	textwidth = 80,
	timeoutlen = 300,
	ttimeoutlen = 0,
	undofile = true,
	updatetime = 200,
	viewoptions = "folds,cursor,curdir,slash,unix",
	virtualedit = "block",
	visualbell = true,
	whichwrap = "h,l,<,>,[,],~",
	wildignore = ".git,.hg,.svn,*.pyc,*.o,*.out,*.jpg,*.jpeg,*.png,*.gif,*.zip,**/tmp/**,*.DS_Store,**/node_modules/**,**/bower_modules/**",
	wildignorecase = true,
	winminwidth = 10,
	winwidth = 30,
	wrap = false,
	writebackup = false,
}

for name, value in pairs(options) do
	vim.api.nvim_set_option_value(name, value, {})
end

vim.g.netrw_liststyle = 3

-- macOS clipboard
vim.g.clipboard = {
	name = "macOS-clipboard",
	copy = { ["+"] = "pbcopy", ["*"] = "pbcopy" },
	paste = { ["+"] = "pbpaste", ["*"] = "pbpaste" },
	cache_enabled = 0,
}
